
---

- name: Stop the Firewall CentOS
  service: name=firewalld state=stopped enabled=False
  when: ansible_os_family == "Redhat"

- name: Stop the Iptables Ubuntu
  service: name=ufw state=stopped
  when: ansible_os_family == "Debain"
